language: python
addons:
  apt:
    packages:
      # install any apt packages on the travis VM here.
      # Install xclip for pyperclip to have access to the clipboard.
      # xclip requires an x-sever, use the xvfb package to run in a framebuffer
      - xclip
      - xvfb
python:
  - "3.7"

# setup installation
install:
  - pip install -r requirements_dev.txt

script: xvfb-run pytest
